# examples/basic_app.toml
[profile_metadata]
title = "Basic demo application"
author = "dimnissv"
version = "0.2.0-beta"
description = "An example of a profile with the main plugins."


[plugins]
local = [
    "./plugins/simple_counter",
    "./plugins/event_listener",
    "./plugins/display_plugin"
]


[config]
theme = "light"
log_level = "DEBUG"

[plugin_configs.simple_counter]
initial_value = 10
step = 2

# Dependencies section (not yet used for sorting)
# [plugins.dependencies]
# simple_counter = "0.1.0"